// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {domain} from '../models';

export function CreateBasketEntry(arg1:application.CreateBasketMovementInput):Promise<Array<domain.Movement>>;

export function CreateBasketExit(arg1:application.CreateBasketMovementInput):Promise<Array<domain.Movement>>;

export function CreateBasketTemplate(arg1:application.CreateBasketTemplateInput):Promise<domain.BasketTemplate>;

export function CreateCategory(arg1:application.CreateCategoryInput):Promise<domain.Category>;

export function CreateDestination(arg1:application.CreateDestinationInput):Promise<domain.Destination>;

export function CreateEntryMovement(arg1:application.CreateMovementInput):Promise<domain.Movement>;

export function CreateEntryMovementsBatch(arg1:application.CreateMovementBatchInput):Promise<Array<domain.Movement>>;

export function CreateExitMovement(arg1:application.CreateMovementInput):Promise<domain.Movement>;

export function CreateExitMovementsBatch(arg1:application.CreateMovementBatchInput):Promise<Array<domain.Movement>>;

export function CreateFamily(arg1:application.CreateFamilyInput):Promise<domain.Family>;

export function CreateOrigin(arg1:application.CreateOriginInput):Promise<domain.Origin>;

export function CreateProduct(arg1:application.CreateProductInput):Promise<domain.Product>;

export function DeactivateBasketTemplate(arg1:string):Promise<void>;

export function DeactivateCategory(arg1:string):Promise<void>;

export function DeactivateDestination(arg1:string):Promise<void>;

export function DeactivateFamily(arg1:string):Promise<void>;

export function DeactivateOrigin(arg1:string):Promise<void>;

export function DeactivateProduct(arg1:string):Promise<void>;

export function ExportBackup(arg1:string):Promise<void>;

export function GetCurrentStock(arg1:application.CurrentStockFilter):Promise<Array<domain.StockItem>>;

export function GetReports(arg1:application.ReportsFilter):Promise<domain.Reports>;

export function GetStockPlanning(arg1:application.StockPlanningFilter):Promise<domain.StockPlanning>;

export function HealthCheck():Promise<Record<string, string>>;

export function ImportBackup(arg1:application.ImportBackupInput):Promise<void>;

export function ListBasketTemplates():Promise<Array<domain.BasketTemplate>>;

export function ListCategories():Promise<Array<domain.Category>>;

export function ListDestinations():Promise<Array<domain.Destination>>;

export function ListFamilies():Promise<Array<domain.Family>>;

export function ListMovements(arg1:application.ListMovementsFilter):Promise<Array<domain.Movement>>;

export function ListOrigins():Promise<Array<domain.Origin>>;

export function ListProducts():Promise<Array<domain.Product>>;

export function UpdateBasketTemplate(arg1:application.UpdateBasketTemplateInput):Promise<domain.BasketTemplate>;

export function UpdateCategory(arg1:application.UpdateCategoryInput):Promise<domain.Category>;

export function UpdateDestination(arg1:application.UpdateDestinationInput):Promise<domain.Destination>;

export function UpdateFamily(arg1:application.UpdateFamilyInput):Promise<domain.Family>;

export function UpdateOrigin(arg1:application.UpdateOriginInput):Promise<domain.Origin>;

export function UpdateProduct(arg1:application.UpdateProductInput):Promise<domain.Product>;
