// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBasketEntry(arg1) {
  return window['go']['app']['App']['CreateBasketEntry'](arg1);
}

export function CreateBasketExit(arg1) {
  return window['go']['app']['App']['CreateBasketExit'](arg1);
}

export function CreateBasketTemplate(arg1) {
  return window['go']['app']['App']['CreateBasketTemplate'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['app']['App']['CreateCategory'](arg1);
}

export function CreateDestination(arg1) {
  return window['go']['app']['App']['CreateDestination'](arg1);
}

export function CreateEntryMovement(arg1) {
  return window['go']['app']['App']['CreateEntryMovement'](arg1);
}

export function CreateEntryMovementsBatch(arg1) {
  return window['go']['app']['App']['CreateEntryMovementsBatch'](arg1);
}

export function CreateExitMovement(arg1) {
  return window['go']['app']['App']['CreateExitMovement'](arg1);
}

export function CreateExitMovementsBatch(arg1) {
  return window['go']['app']['App']['CreateExitMovementsBatch'](arg1);
}

export function CreateFamily(arg1) {
  return window['go']['app']['App']['CreateFamily'](arg1);
}

export function CreateOrigin(arg1) {
  return window['go']['app']['App']['CreateOrigin'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['app']['App']['CreateProduct'](arg1);
}

export function DeactivateBasketTemplate(arg1) {
  return window['go']['app']['App']['DeactivateBasketTemplate'](arg1);
}

export function DeactivateCategory(arg1) {
  return window['go']['app']['App']['DeactivateCategory'](arg1);
}

export function DeactivateDestination(arg1) {
  return window['go']['app']['App']['DeactivateDestination'](arg1);
}

export function DeactivateFamily(arg1) {
  return window['go']['app']['App']['DeactivateFamily'](arg1);
}

export function DeactivateOrigin(arg1) {
  return window['go']['app']['App']['DeactivateOrigin'](arg1);
}

export function DeactivateProduct(arg1) {
  return window['go']['app']['App']['DeactivateProduct'](arg1);
}

export function ExportBackup(arg1) {
  return window['go']['app']['App']['ExportBackup'](arg1);
}

export function GetCurrentStock(arg1) {
  return window['go']['app']['App']['GetCurrentStock'](arg1);
}

export function GetReports(arg1) {
  return window['go']['app']['App']['GetReports'](arg1);
}

export function GetStockPlanning(arg1) {
  return window['go']['app']['App']['GetStockPlanning'](arg1);
}

export function HealthCheck() {
  return window['go']['app']['App']['HealthCheck']();
}

export function ImportBackup(arg1) {
  return window['go']['app']['App']['ImportBackup'](arg1);
}

export function ListBasketTemplates() {
  return window['go']['app']['App']['ListBasketTemplates']();
}

export function ListCategories() {
  return window['go']['app']['App']['ListCategories']();
}

export function ListDestinations() {
  return window['go']['app']['App']['ListDestinations']();
}

export function ListFamilies() {
  return window['go']['app']['App']['ListFamilies']();
}

export function ListMovements(arg1) {
  return window['go']['app']['App']['ListMovements'](arg1);
}

export function ListOrigins() {
  return window['go']['app']['App']['ListOrigins']();
}

export function ListProducts() {
  return window['go']['app']['App']['ListProducts']();
}

export function UpdateBasketTemplate(arg1) {
  return window['go']['app']['App']['UpdateBasketTemplate'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['app']['App']['UpdateCategory'](arg1);
}

export function UpdateDestination(arg1) {
  return window['go']['app']['App']['UpdateDestination'](arg1);
}

export function UpdateFamily(arg1) {
  return window['go']['app']['App']['UpdateFamily'](arg1);
}

export function UpdateOrigin(arg1) {
  return window['go']['app']['App']['UpdateOrigin'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['app']['App']['UpdateProduct'](arg1);
}
