// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignFamilyGroup(arg1, arg2) {
  return window['go']['main']['App']['AssignFamilyGroup'](arg1, arg2);
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function ChooseBackupDestination() {
  return window['go']['main']['App']['ChooseBackupDestination']();
}

export function ChooseRestoreSource() {
  return window['go']['main']['App']['ChooseRestoreSource']();
}

export function CreateAssistentialWork(arg1, arg2) {
  return window['go']['main']['App']['CreateAssistentialWork'](arg1, arg2);
}

export function CreateFamily(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateFamily'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateInstitution(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateInstitution'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateMovement(arg1) {
  return window['go']['main']['App']['CreateMovement'](arg1);
}

export function CreateProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProduct'](arg1, arg2, arg3);
}

export function CreateProductGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateProductGroup'](arg1, arg2);
}

export function CreateProductVariation(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProductVariation'](arg1, arg2, arg3);
}

export function GetAssistentialWorkOutflowKg() {
  return window['go']['main']['App']['GetAssistentialWorkOutflowKg']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetMonthlyDemandProjection() {
  return window['go']['main']['App']['GetMonthlyDemandProjection']();
}

export function GetMonthlyMovementFlowKg() {
  return window['go']['main']['App']['GetMonthlyMovementFlowKg']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetStockCoverageCheck() {
  return window['go']['main']['App']['GetStockCoverageCheck']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAssistentialWorks(arg1) {
  return window['go']['main']['App']['ListAssistentialWorks'](arg1);
}

export function ListFamilies(arg1, arg2) {
  return window['go']['main']['App']['ListFamilies'](arg1, arg2);
}

export function ListFamilyGroupAssignments(arg1) {
  return window['go']['main']['App']['ListFamilyGroupAssignments'](arg1);
}

export function ListInstitutions(arg1) {
  return window['go']['main']['App']['ListInstitutions'](arg1);
}

export function ListMovementGroupItemResolutions(arg1) {
  return window['go']['main']['App']['ListMovementGroupItemResolutions'](arg1);
}

export function ListMovementGroupItems(arg1) {
  return window['go']['main']['App']['ListMovementGroupItems'](arg1);
}

export function ListMovementProductItems(arg1) {
  return window['go']['main']['App']['ListMovementProductItems'](arg1);
}

export function ListMovements(arg1, arg2) {
  return window['go']['main']['App']['ListMovements'](arg1, arg2);
}

export function ListProductGroupItems(arg1) {
  return window['go']['main']['App']['ListProductGroupItems'](arg1);
}

export function ListProductGroups(arg1) {
  return window['go']['main']['App']['ListProductGroups'](arg1);
}

export function ListProductVariationsByProduct(arg1, arg2) {
  return window['go']['main']['App']['ListProductVariationsByProduct'](arg1, arg2);
}

export function ListProducts(arg1) {
  return window['go']['main']['App']['ListProducts'](arg1);
}

export function ListVariationStockStatus(arg1) {
  return window['go']['main']['App']['ListVariationStockStatus'](arg1);
}

export function RemoveProductGroupItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveProductGroupItem'](arg1, arg2);
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function RetryDatabaseInitialization() {
  return window['go']['main']['App']['RetryDatabaseInitialization']();
}

export function SetAssistentialWorkActive(arg1, arg2) {
  return window['go']['main']['App']['SetAssistentialWorkActive'](arg1, arg2);
}

export function SetFamilyActive(arg1, arg2) {
  return window['go']['main']['App']['SetFamilyActive'](arg1, arg2);
}

export function SetInstitutionActive(arg1, arg2) {
  return window['go']['main']['App']['SetInstitutionActive'](arg1, arg2);
}

export function SetProductActive(arg1, arg2) {
  return window['go']['main']['App']['SetProductActive'](arg1, arg2);
}

export function SetProductGroupActive(arg1, arg2) {
  return window['go']['main']['App']['SetProductGroupActive'](arg1, arg2);
}

export function SetProductVariationActive(arg1, arg2) {
  return window['go']['main']['App']['SetProductVariationActive'](arg1, arg2);
}

export function UpdateAssistentialWork(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAssistentialWork'](arg1, arg2, arg3);
}

export function UpdateFamily(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFamily'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateInstitution(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateInstitution'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3, arg4);
}

export function UpdateProductGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProductGroup'](arg1, arg2, arg3);
}

export function UpdateProductVariation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProductVariation'](arg1, arg2, arg3);
}

export function UpsertProductGroupItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpsertProductGroupItem'](arg1, arg2, arg3);
}
