// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';
import {db} from '../models';

export function AssignFamilyGroup(arg1:number,arg2:number):Promise<models.FamilyGroupAssignment>;

export function BackupDatabase(arg1:string):Promise<string>;

export function ChooseBackupDestination():Promise<string>;

export function ChooseRestoreSource():Promise<string>;

export function CreateAssistentialWork(arg1:string,arg2:string):Promise<models.AssistentialWork>;

export function CreateFamily(arg1:number,arg2:string,arg3:number,arg4:string,arg5:string):Promise<models.Family>;

export function CreateInstitution(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Institution>;

export function CreateMovement(arg1:services.CreateMovementInput):Promise<models.Movement>;

export function CreateProduct(arg1:string,arg2:string,arg3:string):Promise<models.Product>;

export function CreateProductGroup(arg1:string,arg2:string):Promise<models.ProductGroup>;

export function CreateProductVariation(arg1:number,arg2:string,arg3:number):Promise<models.ProductVariation>;

export function GetAssistentialWorkOutflowKg():Promise<Array<services.AssistentialWorkOutflowKgItem>>;

export function GetDatabasePath():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetMonthlyDemandProjection():Promise<Array<services.MonthlyDemandItem>>;

export function GetMonthlyMovementFlowKg():Promise<Array<services.MonthlyMovementFlowKgItem>>;

export function GetStartupStatus():Promise<main.AppStartupStatus>;

export function GetStockCoverageCheck():Promise<Array<services.StockCoverageItem>>;

export function Greet(arg1:string):Promise<string>;

export function ListAssistentialWorks(arg1:boolean):Promise<Array<models.AssistentialWork>>;

export function ListFamilies(arg1:boolean,arg2:number):Promise<Array<models.Family>>;

export function ListFamilyGroupAssignments(arg1:number):Promise<Array<models.FamilyGroupAssignment>>;

export function ListInstitutions(arg1:boolean):Promise<Array<models.Institution>>;

export function ListMovementGroupItemResolutions(arg1:number):Promise<Array<models.MovementGroupItemResolution>>;

export function ListMovementGroupItems(arg1:number):Promise<Array<models.MovementGroupItem>>;

export function ListMovementProductItems(arg1:number):Promise<Array<models.MovementProductItem>>;

export function ListMovements(arg1:string,arg2:number):Promise<Array<models.Movement>>;

export function ListProductGroupItems(arg1:number):Promise<Array<models.ProductGroupItem>>;

export function ListProductGroups(arg1:boolean):Promise<Array<models.ProductGroup>>;

export function ListProductVariationsByProduct(arg1:number,arg2:boolean):Promise<Array<models.ProductVariation>>;

export function ListProducts(arg1:boolean):Promise<Array<models.Product>>;

export function ListVariationStockStatus(arg1:boolean):Promise<Array<services.VariationStockStatus>>;

export function RemoveProductGroupItem(arg1:number,arg2:number):Promise<void>;

export function RestoreDatabase(arg1:string):Promise<db.RestoreResult>;

export function RetryDatabaseInitialization():Promise<main.AppStartupStatus>;

export function SetAssistentialWorkActive(arg1:number,arg2:boolean):Promise<void>;

export function SetFamilyActive(arg1:number,arg2:boolean):Promise<void>;

export function SetInstitutionActive(arg1:number,arg2:boolean):Promise<void>;

export function SetProductActive(arg1:number,arg2:boolean):Promise<void>;

export function SetProductGroupActive(arg1:number,arg2:boolean):Promise<void>;

export function SetProductVariationActive(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAssistentialWork(arg1:number,arg2:string,arg3:string):Promise<models.AssistentialWork>;

export function UpdateFamily(arg1:number,arg2:string,arg3:number,arg4:string,arg5:string):Promise<models.Family>;

export function UpdateInstitution(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<models.Institution>;

export function UpdateProduct(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.Product>;

export function UpdateProductGroup(arg1:number,arg2:string,arg3:string):Promise<models.ProductGroup>;

export function UpdateProductVariation(arg1:number,arg2:string,arg3:number):Promise<models.ProductVariation>;

export function UpsertProductGroupItem(arg1:number,arg2:number,arg3:number):Promise<models.ProductGroupItem>;
